-- ============================================
-- DecodeLabs Project 3 - SQL Data Analysis
-- ============================================

-- Query 1: Display all records
SELECT * FROM Orders;

-- Query 2: Display first 10 records
SELECT * FROM Orders
LIMIT 10;

-- Query 3: Display only Product and TotalPrice
SELECT Product, TotalPrice
FROM Orders;

-- Query 4: Orders with TotalPrice greater than 1000
SELECT *
FROM Orders
WHERE TotalPrice > 1000;

-- Query 5: Delivered orders
SELECT *
FROM Orders
WHERE OrderStatus = 'Delivered';

-- Query 6: Orders paid using Credit Card
SELECT *
FROM Orders
WHERE PaymentMethod = 'Credit Card';

-- Query 7: Orders sorted by TotalPrice (Highest First)
SELECT *
FROM Orders
ORDER BY TotalPrice DESC;

-- Query 8: Orders sorted by Date
SELECT *
FROM Orders
ORDER BY Date;

-- Query 9: Count total orders
SELECT COUNT(*) AS TotalOrders
FROM Orders;

-- Query 10: Total Revenue
SELECT SUM(TotalPrice) AS TotalRevenue
FROM Orders;
-- ============================================
-- PART 2 : GROUP BY & AGGREGATE FUNCTIONS
-- ============================================

-- Query 11: Number of orders for each product
SELECT Product, COUNT(*) AS TotalOrders
FROM Orders
GROUP BY Product;

-- Query 12: Total revenue generated by each product
SELECT Product, SUM(TotalPrice) AS Revenue
FROM Orders
GROUP BY Product
ORDER BY Revenue DESC;

-- Query 13: Average order value for each product
SELECT Product, AVG(TotalPrice) AS AveragePrice
FROM Orders
GROUP BY Product
ORDER BY AveragePrice DESC;

-- Query 14: Number of orders by payment method
SELECT PaymentMethod, COUNT(*) AS TotalOrders
FROM Orders
GROUP BY PaymentMethod;

-- Query 15: Revenue by payment method
SELECT PaymentMethod, SUM(TotalPrice) AS Revenue
FROM Orders
GROUP BY PaymentMethod
ORDER BY Revenue DESC;

-- Query 16: Number of orders by status
SELECT OrderStatus, COUNT(*) AS TotalOrders
FROM Orders
GROUP BY OrderStatus;

-- Query 17: Average quantity ordered for each product
SELECT Product, AVG(Quantity) AS AverageQuantity
FROM Orders
GROUP BY Product;

-- Query 18: Highest and lowest TotalPrice
SELECT
MAX(TotalPrice) AS HighestPrice,
MIN(TotalPrice) AS LowestPrice
FROM Orders;

-- Query 19: Products with more than 170 orders
SELECT Product, COUNT(*) AS TotalOrders
FROM Orders
GROUP BY Product
HAVING COUNT(*) > 170;

-- Query 20: Referral sources and total orders
SELECT ReferralSource, COUNT(*) AS TotalOrders
FROM Orders
GROUP BY ReferralSource
ORDER BY TotalOrders DESC;
-- ============================================
-- PART 3 : ADVANCED SQL QUERIES
-- ============================================

-- Query 21: Total revenue by Referral Source
SELECT ReferralSource,
       SUM(TotalPrice) AS TotalRevenue
FROM Orders
GROUP BY ReferralSource
ORDER BY TotalRevenue DESC;

-- Query 22: Average TotalPrice by Payment Method
SELECT PaymentMethod,
       AVG(TotalPrice) AS AverageRevenue
FROM Orders
GROUP BY PaymentMethod
ORDER BY AverageRevenue DESC;

-- Query 23: Orders with Quantity greater than 3
SELECT *
FROM Orders
WHERE Quantity > 3;

-- Query 24: Orders between ₹500 and ₹1500
SELECT *
FROM Orders
WHERE TotalPrice BETWEEN 500 AND 1500;

-- Query 25: Monthly Revenue
SELECT
    YEAR(Date) AS Year,
    MONTH(Date) AS Month,
    SUM(TotalPrice) AS Revenue
FROM Orders
GROUP BY YEAR(Date), MONTH(Date)
ORDER BY Year, Month;

-- Query 26: Top 5 Highest Value Orders
SELECT *
FROM Orders
ORDER BY TotalPrice DESC
LIMIT 5;

-- Query 27: Product-wise Maximum Price
SELECT Product,
       MAX(TotalPrice) AS HighestSale
FROM Orders
GROUP BY Product
ORDER BY HighestSale DESC;

-- Query 28: Product-wise Minimum Price
SELECT Product,
       MIN(TotalPrice) AS LowestSale
FROM Orders
GROUP BY Product
ORDER BY LowestSale;

-- Query 29: Customers with multiple orders
SELECT CustomerID,
       COUNT(*) AS OrdersPlaced
FROM Orders
GROUP BY CustomerID
HAVING COUNT(*) > 1
ORDER BY OrdersPlaced DESC;

-- Query 30: Overall Business Summary
SELECT
    COUNT(*) AS TotalOrders,
    SUM(TotalPrice) AS TotalRevenue,
    AVG(TotalPrice) AS AverageOrderValue,
    MAX(TotalPrice) AS HighestOrder,
    MIN(TotalPrice) AS LowestOrder
FROM Orders;